[build]
  publish = "build/web"
  command = """
  set -e

  export PATH="$HOME/flutter/bin:$PATH"
  export PATH="$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"

  if [ ! -d "$HOME/flutter" ]; then
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 "$HOME/flutter"
  fi

  flutter --version
  flutter config --enable-web
  flutter config --no-analytics
  flutter pub get
flutter run build_web --dart-define=SAS_PROXY_TOKEN=104199 --dart-define=SAS_WEB_PROXY_URL=https://ha-0cs7.onrender.com

  """
