name: untitled
description: "wakel-iq ISP subscriber manager"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.1.2
  file_picker: ^8.1.3
  http: ^1.2.2
  flutter_network_speed_test: 0.2.0
  web: ^1.1.1
  dart_ping: 9.0.1
  dart_ping_ios: 4.0.2
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  excel: ^4.0.6
  file_saver: ^0.4.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  firebase_database: ^12.4.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.4.6
  firebase_functions: ^0.0.1-dev
  cloud_functions: ^6.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
