// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvFNaOjKqYATyEteyVXLoH5aqi8qXNlY',
    appId: '1:297741444994:android:1b5c604c227f0081c0919b',
    messagingSenderId: '297741444994',
    projectId: 'wakeiq-4b97b',
    databaseURL: 'https://wakeiq-4b97b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wakeiq-4b97b.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcV1XkILsjalRqZtJl7xAuUu3yJd2u30',
    appId: '1:297741444994:web:d73cfd79b421f24bc0919b',
    messagingSenderId: '297741444994',
    projectId: 'wakeiq-4b97b',
    authDomain: 'wakeiq-4b97b.firebaseapp.com',
    databaseURL: 'https://wakeiq-4b97b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wakeiq-4b97b.firebasestorage.app',
    measurementId: 'G-9X99HXGD7V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSJxbsGOmtKMEDl8zq6sqTOVIW5rrlcY',
    appId: '1:297741444994:ios:8aabc59f21be2efcc0919b',
    messagingSenderId: '297741444994',
    projectId: 'wakeiq-4b97b',
    databaseURL: 'https://wakeiq-4b97b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wakeiq-4b97b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
